from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    HRFlowable,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

import os


def create_pdf(company, insights):

    # =========================
    # CREATE REPORTS FOLDER
    # =========================

    os.makedirs("generated_reports", exist_ok=True)

    output_path = os.path.join(
        "generated_reports",
        f"{company}.pdf"
    )

    # =========================
    # PDF SETUP
    # =========================

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=45,
        leftMargin=45,
        topMargin=40,
        bottomMargin=35
    )

    styles = getSampleStyleSheet()

    # =========================
    # BODY STYLE
    # =========================

    body_style = styles['BodyText']

    body_style.fontName = 'Times-Roman'
    body_style.fontSize = 11
    body_style.leading = 15
    body_style.textColor = colors.black

    content = []

    # =========================
    # COVER PAGE
    # =========================

    title = Paragraph(
        f"""
        <font size=28 color='#2563eb'>
        <b>{company}</b>
        </font>
        """,
        styles['Title']
    )

    subtitle = Paragraph(
        """
        <para align='center'>
        <font size=18 color='grey'>
        AI-Powered Business Audit Report
        </font>
        </para>
        """,
        body_style
    )

    content.append(Spacer(1, 140))

    content.append(title)

    content.append(Spacer(1, 10))

    content.append(subtitle)

    content.append(Spacer(1, 220))

    

    content.append(PageBreak())

    # =========================
    # EXECUTIVE SUMMARY HEADER
    # =========================

    heading = Paragraph(
        """
        <font size=20 color='#2563eb'>
        <b>Executive Summary</b>
        </font>
        """,
        styles['Heading1']
    )

    content.append(heading)

    content.append(Spacer(1, 4))

    line = HRFlowable(
        width="100%",
        thickness=1.2,
        color=colors.HexColor('#2563eb')
    )

    content.append(line)

    content.append(Spacer(1, 10))

    # =========================
    # COMPANY INFO TABLE
    # =========================

    data = [
        ["Company", company],
        ["Audit Type", "AI Business Intelligence Report"],
        ["Generated By", "Lead Automation Platform"]
    ]

    table = Table(
        data,
        colWidths=[180, 280]
    )

    table.setStyle(TableStyle([

        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563eb')),

        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),

        ('FONTNAME', (0, 0), (-1, -1), 'Times-Roman'),

        ('FONTSIZE', (0, 0), (-1, -1), 11),

        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),

        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),

        ('BOX', (0, 0), (-1, -1), 1.2, colors.HexColor('#2563eb')),

        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.grey),

    ]))

    content.append(table)

    content.append(Spacer(1, 18))

    # =========================
    # BUSINESS INSIGHTS HEADER
    # =========================

    insights_title = Paragraph(
        """
        <font size=18 color='#2563eb'>
        <b>Business Insights</b>
        </font>
        """,
        styles['Heading2']
    )

    content.append(insights_title)

    content.append(Spacer(1, 4))

    line2 = HRFlowable(
        width="100%",
        thickness=1.2,
        color=colors.HexColor('#2563eb')
    )

    content.append(line2)

    content.append(Spacer(1, 10))

    # =========================
    # CLEAN & FORMAT AI CONTENT
    # =========================

    formatted_insights = insights

    # Remove markdown bold symbols
    formatted_insights = formatted_insights.replace("**", "")

    # Section heading styles
    section_styles = {

        "Executive Summary":
        "<font color='#2563eb' size='15'><b>Executive Summary</b></font>",

        "Business Strengths":
        "<font color='#2563eb' size='15'><b>Business Strengths</b></font>",

        "Potential Challenges":
        "<font color='#2563eb' size='15'><b>Potential Challenges</b></font>",

        "AI Automation Opportunities":
        "<font color='#2563eb' size='15'><b>AI Automation Opportunities</b></font>",

        "Customer Experience & Digital Presence":
        "<font color='#2563eb' size='15'><b>Customer Experience & Digital Presence</b></font>",

        "Strategic Recommendations":
        "<font color='#2563eb' size='15'><b>Strategic Recommendations</b></font>"
    }

    for old, new in section_styles.items():
        formatted_insights = formatted_insights.replace(old, new)

    # Reduce spacing
    formatted_insights = formatted_insights.replace(
        "\n",
        "<br/>"
    )

    insights_paragraph = Paragraph(
        formatted_insights,
        body_style
    )

    # =========================
    # TOP BORDER
    # =========================

    box_top = HRFlowable(
        width="100%",
        thickness=1.2,
        color=colors.HexColor('#2563eb')
    )

    content.append(box_top)

    content.append(Spacer(1, 6))

    # =========================
    # INSIGHTS CONTENT
    # =========================

    content.append(insights_paragraph)

    content.append(Spacer(1, 6))

    # =========================
    # BOTTOM BORDER
    # =========================

    box_bottom = HRFlowable(
        width="100%",
        thickness=1.2,
        color=colors.HexColor('#2563eb')
    )

    content.append(box_bottom)

    content.append(Spacer(1, 20))

    # =========================
    # FOOTER
    # =========================

    

    # =========================
    # BUILD PDF
    # =========================

    doc.build(content)

    return output_path